site_name: Документация
nav:
  - Общая информация: gi/index.md
  - Руководство пользователя: ug/index.md
  - Руководство по установке, настройке и интеграции: aag/index.md
  - Рекомендации по безопасной разработке:
    - rg/index.md
    - Рекомендации для Android:
      - rg/ru/android/index.md
      - Небезопасное хранение ключевой информации:
        - rg/ru/android/a_writable_keystore.md
        - rg/ru/android/a_keystore_with_write_permission_protected_by_a_weak_password.md
        - rg/ru/android/readable_file_keystore.md
        - rg/ru/android/a_readable_keystore,_protected_by_a_weak_password,_with_private_keys.md
        - rg/ru/android/a_readable_keystore,_protected_by_a_weak_password,_with_public_keys.md
        - rg/ru/android/a_readable_keystore_containing_private_keys_protected_by_a_weak_password.md
        - rg/ru/android/using_a_file_keystore.md
        - rg/ru/android/a_keystore,_protected_by_weak_password,_containing_private_keys.md
        - rg/ru/android/a_keystore_with_write_permission_protected_by_a_weak_password.md
        - rg/ru/android/a_keystore,_protected_by_weak_password,_containing_public_keys.md
        - rg/ru/android/a_keystore_containing_private_keys_protected_by_a_weak_password.md
      - Передача sensitive-информации в Activity:
        - rg/ru/android/insecure_transmission_of_sensitive_information_in_activity.md
        - rg/ru/android/insecure_transmission_of_sensitive_information_in_external_activity.md
        - rg/ru/android/insecure_transmission_of_sensitive_information_in_private_activity.md
      - Передача sensitive-информации в Service:
        - rg/ru/android/insecure_transmission_of_sensitive_information_in_service.md
        - rg/ru/android/insecure_transmission_of_sensitive_information_in_external_service.md
        - rg/ru/android/insecure_transmission_of_sensitive_information_in_internal_service.md
      - Передача sensitive-информации по сети:
        - rg/ru/android/inclusion_of_sensitive_information_into_the_get_request_parameters.md
        - rg/ru/android/inclusion_of_sensitive_information_into_an_https_request.md
    - Рекомендации для iOS:
      - rg/ru/ios/index.md

theme:
  language: ru
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: stingray
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.shares
    - content.code.annotate
# Убрать правую колонку
#    - toc.integrate
#    - navigation.sections
extra_css:
  - stylesheets/extra.css
#  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

plugins:
  - git-revision-date-localized:
      type: iso_datetime
  - search:
      lang: 
        - en
        - ru

# extra:
#  social:
#    - icon: fontawesome/brands/twitter 
#      link: https://twitter.com/squidfunk
#    - icon: fontawesome/brands/github 
#      link: https://twitter.com/squidfunk

markdown_extensions:
  - meta
  - abbr
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      use_pygments: false
      auto_title: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: ⚓︎

extra_javascript:
#  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
#  - javascripts/highlight.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js

# repo_url: https://github.com/andreygladilin/mktest
# repo_name: andreygladilin/mktest